### ISSUE TITLE
bibtex.php issue

### ISSUE THREAD

**Issue by VadoLigure** [dwp-forge/refnotes#60] opened 2020-10-04 08:16 UTC
Dokuwiki: 2018.04.22-0124
Theme: sprintdoc
refnotes: 2020-08-10

After installing plugin the whole wiki gets unreacheable and useless. I get the following error:

Fatal error: Class 'dokuwiki\Parsing\Parser' not found in /volume1/web/dokuwiki/lib/plugins/refnotes/bibtex.php on line 11 

Any advice?
Thanks!

**Comment by dwp-forge** [comment] 2020-10-04 08:54
Duplicate of #54.

Update DW or use older plugin version.

**Comment by VadoLigure** [comment] 2020-10-04 09:26
It works. Thank you very much and forgive the duplication.

Regards

**Closed** 2020-10-04 09:26 UTC
Labels: duplicate, wontfix
