### ISSUE TITLE
Dokuwiki errror after updating refnotes

### ISSUE THREAD

**Issue by TStein1984** [dwp-forge/refnotes#57] opened 2020-08-15 13:12 UTC
After updating refnotes I get the error message 

Fatal error: Class 'dokuwiki\Parsing\Parser' not found in /volume1/web/dokuwiki/lib/plugins/refnotes/bibtex.php on line 11 

when I'll try to start dokuwiki. What can be the reason for it and how can I fix it?

Thank you in advance and best regards

**Comment by dwp-forge** [comment] 2020-08-15 16:46
Duplicate of #54.

**Closed** 2021-05-16 18:07 UTC
Labels: duplicate, wontfix
